# Generated by Django 6.0.4 on 2026-04-21 11:21

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('txtype', models.CharField(choices=[('TOPUP', "Hisob To'ldirish"), ('TRANSFER', "Pul O'tkazish"), ('WITHDRAW', 'Pul Yechish')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('SUCCESS', 'Bajarildi'), ('FAILED', 'Muvaffaqiyatsiz'), ('REVERSED', 'Qaytarildi')], default='PENDING', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('reference', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to='wallet.wallet')),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to='wallet.wallet')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_time'],
                'indexes': [models.Index(fields=['from_wallet', '-created_time'], name='transaction_from_wa_7f2128_idx'), models.Index(fields=['to_wallet', '-created_time'], name='transaction_to_wall_4dbb52_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx'), models.Index(fields=['idempotency_key'], name='transaction_idempot_d892f2_idx')],
            },
        ),
    ]
