# Generated by Django 6.0.4 on 2026-04-24 18:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('card_holder_name', models.CharField(max_length=100)),
                ('expiry_month', models.PositiveSmallIntegerField()),
                ('expiry_year', models.PositiveSmallIntegerField()),
                ('card_type', models.CharField(choices=[('virtual', 'Virtual karta'), ('physical', 'Physical')], default='virtual', max_length=8)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='wallet.wallet')),
            ],
            options={
                'db_table': 'cards',
            },
        ),
    ]
